; Entorno Local (Comentado para subir a produccion)
; hostname='127.0.0.1'
; username='root'
; password=''
; database='preguntadosMundial'
; baseUrl="/preguntadosPW2"
; mail_user="13b6c5f52b7e9e"
; mail_pass="c9041c1603f335"

; Entorno Produccion InfinityFree
 hostname='sql102.infinityfree.com'
 username='if0_42141863'
 password='Pr3gunt4d0sPw2'
 database='if0_42141863_preguntadospw2'
 mail_user="13b6c5f52b7e9e"
 mail_pass="c9041c1603f335"
