; Entorno Local (Comentado para subir a produccion)
 hostname='127.0.0.1'
 username='root'
 password=''
 database='preguntadosMundial'
 baseUrl="/preguntadosPW2"

; hostname='127.0.0.1'
; username='root'
; password=''
; database='preguntadosMundial'
; baseUrl="/preguntadosPW2"
; mail_user="77dd969e964dd3"
; mail_pass="7f0374dc7dd638"

