; Entorno Local (Comentado para subir a produccion)
; hostname='127.0.0.1:3307'
; username='root'
; password=''
; database='preguntadosMundial'

; Entorno Produccion InfinityFree
hostname='sql102.infinityfree.com'
username='if0_42141863'
password='TU_CONTRASEÑA_AQUI'
database='if0_42141863_preguntados'
